# Generated by Django 4.2.16 on 2024-12-19 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=30)),
                ('intro', models.CharField(default='', max_length=100)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2024, 12, 19, 7, 5, 49, 929231))),
                ('reviewer', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField(choices=[(1, '待处理'), (2, '进行中'), (3, '已完成'), (4, '已废弃')], default=0)),
            ],
        ),
    ]
